<?php

namespace Database\Seeders;

use App\Enums\OfficeRankEnum;
use App\Models\MasterData\Office;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;

class OfficeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        collect([
            [
                'name' => 'Pemerintah Kabupaten Donggala',
                'alias' => 'Pemda Donggala',
                'rank' => OfficeRankEnum::PEMKAB->value,
                'address' => 'Jl. Jati, Kompleks Perkantoran Pemda Kelurahan Gunung Bale Banawa',
                'phone' => null,
                'site_url' => 'https://donggala.go.id',
            ],
            [
                'name' => 'Sekretariat Daerah',
                'alias' => 'Setda',
                'rank' => OfficeRankEnum::SETDA->value,
                'address' => null,
                'phone' => null,
                'site_url' => 'https://donggala.go.id',
            ],
            [
                'name' => 'Dinas Komunikasi dan Informatika',
                'alias' => 'Diskominfo',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => 'Jl. Jati No. 14 Kel. Gunung Bale, Kec. Banawa, Kab. Donggala',
                'phone' => null,
                'site_url' => 'https://kominfo.donggala.go.id',
            ],
            [
                'name' => 'Dinas Perhubungan',
                'alias' => 'Dishub',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => 'Jl. Kabonga Besar, Kec. Banawa, Kabupaten Donggala',
                'phone' => null,
                'site_url' => 'https://dishubdonggala.com',
            ],
            [
                'name' => 'Dinas Kesehatan',
                'alias' => 'Dinkes',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Dinas Pendidikan, Pemuda dan Olahraga',
                'alias' => 'Disdikpora',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Dinas Pekerjaan Umum dan Penataan Ruang',
                'alias' => 'Dinas PUPR',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Dinas Lingkungan Hidup, Pertanahan, Perumahan dan Kawasan Permukiman',
                'alias' => 'DLHPPKP',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Satuan Polisi Pamong Praja',
                'alias' => 'Satpol PP',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Dinas Sosial, Pemberdayaan Masyarakat dan Desa',
                'alias' => 'Dinsos PMD',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Dinas Tenaga Kerja dan Transmigrasi',
                'alias' => 'Disnakertrans',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Dinas Pengendalian Penduduk, Keluarga Berencana, Pemberdayaan Perempuan dan Perlindungan Anak',
                'alias' => 'DP2KBP3A',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Dinas Ketahanan Pangan',
                'alias' => 'DKP',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Dinas Kependudukan dan Pencatatan Sipil',
                'alias' => 'Disdukcapil',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Dinas Perindustrian, Perdagangan, Koperasi, Usaha Mikro Kecil dan Menengah',
                'alias' => 'Dinas PPKUKM',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu',
                'alias' => 'DPMPTSP',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Dinas Perpustakaan dan Kearsipan',
                'alias' => 'Dispusip',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Dinas Perikanan',
                'alias' => 'Diskan',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Dinas Pariwisata, Kebudayaan dan Ekonomi Kreatif',
                'alias' => 'Disparbudekraf',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Dinas Pertanian',
                'alias' => 'Dispertan',
                'rank' => OfficeRankEnum::DINAS->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Badan Pengelolaan Keuangan dan Aset Daerah',
                'alias' => 'BPKAD',
                'rank' => OfficeRankEnum::BADAN->value,
                'address' => 'Jl. Jati No. 1, Gunung Bale, Kec. Banawa, Kabupaten Donggala',
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Badan Kepegawaian dan Pengembangan Sumber Daya Manusia',
                'alias' => 'BKPSDM',
                'rank' => OfficeRankEnum::BADAN->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Badan Perencanaan Pembangunan, Riset dan Inovasi Daerah',
                'alias' => 'BPPRID',
                'rank' => OfficeRankEnum::BADAN->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Badan Pendapatan Daerah',
                'alias' => 'Bapenda',
                'rank' => OfficeRankEnum::BADAN->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Badan Penanggulangan Bencana Daerah',
                'alias' => 'BPBD',
                'rank' => OfficeRankEnum::BADAN->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Badan Kesatuan Bangsa dan Politik',
                'alias' => 'BKBP',
                'rank' => OfficeRankEnum::BADAN->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Kecamatan Banawa',
                'alias' => 'Banawa',
                'rank' => OfficeRankEnum::KECAMATAN->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Kecamatan Banawa Tengah',
                'alias' => 'Banawa Tengah',
                'rank' => OfficeRankEnum::KECAMATAN->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Desa Loli Dondo',
                'alias' => 'Loli Dondo',
                'rank' => OfficeRankEnum::DESA->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Desa Toaya',
                'alias' => 'Toaya',
                'rank' => OfficeRankEnum::DESA->value,
                'address' => 'Jl. Pue Lasadindi No.19, Kec. Sindue, Kab. Donggala',
                'phone' => '+6281314560100',
                'site_url' => 'https://toaya-sindue.desa.id',
            ],
            [
                'name' => 'Desa Towale',
                'alias' => 'Towale',
                'rank' => OfficeRankEnum::DESA->value,
                'address' => null,
                'phone' => null,
                'site_url' => 'https://towale.digitaldesa.id',
            ],
            [
                'name' => 'Kelurahan Boneoge',
                'alias' => 'Boneoge',
                'rank' => OfficeRankEnum::KELURAHAN->value,
                'address' => null,
                'phone' => null,
                'site_url' => null,
            ],
            [
                'name' => 'Kelurahan Ganti',
                'alias' => 'Ganti',
                'rank' => OfficeRankEnum::KELURAHAN->value,
                'address' => 'Jl. Trans Sulawesi Donggala',
                'phone' => null,
                'site_url' => null,
            ],
        ])->each(function ($office) {
            $of = Office::firstOrCreate(['name' => $office['name']], Arr::except($office, ['name']));
            $this->command->info("\tOffice: {$of->name} (was " . ($of->wasRecentlyCreated ? 'created' : 'existing') . ')');
        });
    }
}
